allowBuilds:
  '@prisma/engines': true
  bcrypt: true
  core-js: true
  prisma: true
  puppeteer: true
  sharp: true
  unrs-resolver: true
onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - bcrypt
  - esbuild
  - prisma
  - puppeteer
  - sharp
  - unrs-resolver
